#! /bin/tcsh

set PAN = /home/projects/mniel/multipred/withMHC/IEDB_retrain_March_2013/random/
set PICK = /home/projects/mniel/pickpocket-1.1_random/

#foreach a ( HLA-B35:45 HLA-B52:08 HLA-C02:16 )
foreach a ( HLA-A02:103 )

set pseudo = `cat /usr/cbs/bio/src/netMHCcons-1.1/data/MHC_pseudo.dat | gawk -v a=$a '$1==a' | head -1 | args 2`

echo $a $pseudo

if ( ! -e $a.pred ) then

if ( -e $PAN/$pseudo.pred.gz ) then

gunzip -c $PAN/$pseudo.pred.gz | xC | args 3,5 | gawk '{printf( "%s %f\n", $1,$2)}' > $$.pan

else 

echo Error. File $pseudo.pred.gz does not exist 

exit

endif

if ( -e $PICK/$pseudo.pred ) then

cat $PICK/$pseudo.pred | gawk '{printf( "%s %f\n", $1,$2)}' > $$.pick

else

echo  Error. File $PICK/$pseudo.pred does not exist 

exit

endif

paste $$.pick $$.pan | gawk '$1 == $3' | gawk '{print $1,($2+$4)/2}' > $a.pred

endif

touch $a.thr
rm -f $a.thr

cat $a.pred | sort -nrk2 > $$.sort

echo $a `wc $$.sort | args 1` 

foreach f ( 0.01 0.025 0.05 0.075 0.1 0.125 0.15 0.175 0.2 0.25 0.3 0.4 0.5 0.8 1.0 1.5 2 3 4 5 6 7 8 9 10 15 16 32 50 )

set N = `echo $f | gawk '{print ($1*200000)/100}' `

set line = `cat $$.sort | head -$N | tail -1`

echo $pseudo $f $line >> $a.thr

end

end
