#! /bin/tcsh -f

# This the main PickPocket 1.1 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2014 September 01	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the PickPocket 1.1 directory (mandatory)
setenv	NMHOME	/home/witold/prog/SysteMHC_Binaries/pickpocket/pickpocket-1.1
# determine where to store temporary files (must be writable to all users)
setenv TMPDIR /home/witold/prog/temp

if ( ${?TMPDIR} == 0 ) then
        setenv  TMPDIR  /scratch
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv PICKPOCKET $NMHOME/$PLATFORM


# main ========================================================================
if ( -x $PICKPOCKET/bin/pickpocket_pmbec ) then
   $PICKPOCKET/bin/pickpocket_pmbec $* -d $PICKPOCKET/data/PMBEC.lib 
else
   echo PickPocket: no binaries found for $PLATFORM $PICKPOCKET/bin/pickpocket_pmbec
endif

# end of script ===============================================================
