#! /bin/tcsh -f

# This the main NetMHCcons 1.1 script. It only acts as the frontend to the
# software proper, a compiled binary.
# 
# VERSION:	2014 Sept 03	launch
# 

###############################################################################
#               GENERAL SETTINGS: CUSTOMIZE TO YOUR SITE
###############################################################################

# full path to the NetMHCcons 1.1 directory (mandatory)
setenv	NCHOME	/usr/cbs/packages/netMHCcons/1.1/netMHCcons-1.1

# full path to the NetMHCpan method (mandatory)
setenv	NETMHCpan_env	/usr/cbs/bio/src/netMHCpan-2.8/netMHCpan

# full path to the NetMHC method (mandatory)
setenv	NETMHC_env	/usr/cbs/bio/src/netMHC-3.4/netMHC

# full path to the PickPocket method (mandatory)
setenv	PICKPOCKET_env	/usr/cbs/bio/src/pickpocket-1.1/PickPocket

# determine where to store temporary files (must be writable to all users)
if ( ${?TMPDIR} == 0 ) then
	setenv  TMPDIR  /scratch
endif

# determine platform (do not change this unless you don't have 'uname'!)
setenv	UNIX	`uname -s`
setenv	AR	`uname -m`

###############################################################################
#               NOTHING SHOULD NEED CHANGING BELOW THIS LINE!
###############################################################################

# other settings
set PLATFORM = `echo $UNIX $AR | awk '{print $1"_"$2}'`
setenv PLATFORM $PLATFORM
setenv NETMHCcons $NCHOME

# main ========================================================================
if ( -x $NETMHCcons/NetMHCcons-1.1.pl ) then
   $NETMHCcons/NetMHCcons-1.1.pl $*
else
   echo NetMHCcons-1.1.pl not found
endif

# end of script ===============================================================
